### ISSUE TITLE
Provide Python implementation

### ISSUE THREAD

**Issue by impredicative** [petered/spiking-mlp#4]
Is it possible to provide a Python implementation, i.e. one that doesn't rely on Java? Thanks.

**Comment by petered** [comment]
Hi Ouroboros,

Afraid not.   The algorithm in this paper is event-based, and would be way
too slow in Python.

However, we do have a similar, non-event based Python implementation at
https://github.com/petered/pdnn

- Peter

**Comment by impredicative** [comment]
Fwiw, [bindsnet](https://github.com/Hananel-Hazan/bindsnet) and [nengo-dl](https://github.com/nengo/nengo-dl), both of which presumably permit spiking architectures, do have a Python API.
